giant eagle: /MonstersE-F#training-a-giant-eagle
giant owl: /MonstersO-R#training-a-giant-owl
griffon: /MonstersG#training-a-griffon
hippogriff: /MonstersH-I#training-a-hippogriff
howler: /MonstersH-I#training-a-howler
pegasus: /MonstersO-R#training-a-pegasus
spider eater: /MonstersS#training-a-spider-eater
